
"""
Django settings for liga_de_cursos project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-6)7-zxjpzdk+u9ikb_)ynoobr%-hvsfr9b9nhvrx4&n4w4-d1g'
SECRET_KEY = os.environ.get("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

RAILWAY_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN", "")


ALLOWED_HOSTS = [h for h in [
    "api.betpraxis.pt",
    "betpraxis.pt",
    "www.betpraxis.pt",
    RAILWAY_DOMAIN,  # ex: web-production-xxx.up.railway.app
] if h]

CSRF_TRUSTED_ORIGINS = [o for o in [
    "https://api.betpraxis.pt",
    "https://betpraxis.pt",
    "https://www.betpraxis.pt",
    f"https://{RAILWAY_DOMAIN}" if RAILWAY_DOMAIN else "",
] if o]

# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',          # <- obrigatório para allauth

    # 3rd party
    'rest_framework',
    'rest_framework.authtoken',      # se usares tokens do dj-rest-auth
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',         # <- ADICIONAR
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # apps do projeto
    'users',
    'liga',
    
    ]
SITE_ID = 1


AUTH_USER_MODEL = 'users.User'

# Serve para validar as credencias de um user, estou a adicionar para permitir login com email em vez de username  
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# --- dj-rest-auth / django-allauth recommended settings ---
# Define os campos obrigatórios para signup
ACCOUNT_SIGNUP_FIELDS = {
    'username': {'required': True},
    'email': {'required': True},
}
# Define os métodos de login compatíveis com os campos obrigatórios
ACCOUNT_LOGIN_METHODS = ['username', 'email']
#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_SIGNUP_FIELDS = ['email']  # sem 'username'
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # para nao enviar email de confirmacao
ACCOUNT_EMAIL_VERIFICATION = "none"
# Configurações do django REST Framework - criar apis, definir autenticacao e permissões
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', # Autenticação token JWT - não se usa csrf ou cookies pq nao funciona bem com nextjs
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # por default so users autenticados podem aceder às APIs
    )
}

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt-refresh',
    'JWT_AUTH_HTTPONLY': False,
    'USER_DETAILS_SERIALIZER': 'users.serializers.CustomUserDetailsSerializer', 
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),      # Tempo do token principal - usado para autenticar requests
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),        # Tempo do token de refresh - se já tiver expirado o access token, pede um novo automaticamente durante 7 dias  
    'ROTATE_REFRESH_TOKENS': True,                      # Gera novo refresh a cada uso
    'BLACKLIST_AFTER_ROTATION': True,                   # Invalida refresh antigo
    'AUTH_HEADER_TYPES': ('Bearer',),                   # Usa "Bearer <token>"
}

REST_USE_JWT = True
REST_AUTH_TOKEN_MODEL = None  # (em algumas versões: TOKEN_MODEL = None)


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',           # <-- vírgula aqui!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <— depois da SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://betpraxis.pt",
    "https://www.betpraxis.pt",
    "https://api.betpraxis.pt",  # para chamadas diretas ao domínio da API
]
# Está atrás de proxy (Railway Metal Edge) — isto garante que o Django reconhece HTTPS:
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ROOT_URLCONF = 'liga_de_cursos.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # opcional
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = 'liga_de_cursos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,   # ok na Railway
        )
    }
else:
    # fallback local: SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Django 5: storage do Whitenoise
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
