# Generated by Django 5.2.5 on 2025-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(choices=[('soc', 'Sociologia'), ('ige', 'Informática e Gestão de Empresas'), ('nenhum', 'Nenhum')], default='nenhum', max_length=50),
        ),
    ]
