# Generated by Django 5.2.5 on 2025-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.CharField(choices=[('soc', 'Sociologia'), ('ige', 'Informática e Gestão de Empresas'), ('por definir', 'por definir')], max_length=50),
        ),
    ]
