# Generated by Django 5.2.5 on 2025-09-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.CharField(choices=[('ant', 'Antropologia'), ('arq', 'Arquitetura'), ('lcd', 'Ciência de Dados'), ('cpo', 'Ciências Politicas'), ('eco', 'Economia'), ('eti', 'Engenharia de Telecomunicações e Informática'), ('lei', 'Engenharia Informática'), ('fin', 'Finanças e Contabilidade'), ('ges', 'Gestão'), ('grh', 'Gestão de Recursos Humanos'), ('gil', 'Gestão Industrial e Logística'), ('gmk', 'Gestão de Marketing'), ('hmc', 'História Moderna e Contemporânea'), ('ige', 'Informática e Gestão de Empresas'), ('psi', 'Psicologia'), ('soc', 'Sociologia'), ('ss', 'Serviço Social'), ('sintra', 'Sintra'), ('por definir', 'por definir')], max_length=50),
        ),
    ]
