# Generated by Django 5.2.5 on 2025-08-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Liga de Cursos', max_length=100)),
                ('season_label', models.CharField(default='2025', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('live', 'A decorrer'), ('finished', 'Terminada')], default='draft', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
                'unique_together': {('title', 'season_label')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pote', models.PositiveSmallIntegerField(choices=[(1, 'Pote 1'), (2, 'Pote 2'), (3, 'Pote 3')])),
                ('points', models.IntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='liga.competition')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='liga.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('GROUP', 'Fase de Grupos'), ('QF', 'Quartos'), ('SF', 'Meias'), ('THIRD', '3º lugar'), ('FINAL', 'Final'), ('TB', 'Desempate')], default='GROUP', max_length=10)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('LIVE', 'A decorrer'), ('FT', 'Final')], default='SCHEDULED', max_length=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='liga.competition')),
                ('curso1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso1_matches', to='liga.competitionentry')),
                ('curso2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso2_matches', to='liga.competitionentry')),
                ('winner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='liga.competitionentry')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='liga.match')),
                ('pick_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_in_votes', to='liga.competitionentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='competitionentry',
            index=models.Index(fields=['competition', 'pote'], name='liga_compet_competi_82739a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('competition', 'curso')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition', 'stage', 'status'], name='liga_match_competi_5120c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('curso1', models.F('curso2')), _negated=True), name='match_distinct_entries'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('winner_entry__isnull', True), ('winner_entry', models.F('curso1')), ('winner_entry', models.F('curso2')), _connector='OR'), name='winner_is_participant'),
        ),
        migrations.AlterUniqueTogether(
            name='matchvote',
            unique_together={('user', 'match')},
        ),
    ]
