# Generated by Django 5.2.5 on 2025-08-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleVoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_questions', to='liga.competition')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_in_simple_votes', to='liga.competitionentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_votes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='liga.simplevotequestion')),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
