# Generated by Django 5.2.5 on 2025-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_simplevotequestion_simplevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='manual_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Se preenchido, força a posição (1=1º).', null=True),
        ),
    ]
