# Generated by Django 5.2.5 on 2025-09-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_competitionentry_manual_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchvote',
            name='odds_at_bet',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='matchvote',
            name='payout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchvote',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchvote',
            name='stake',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='odds_at_bet',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='payout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simplevote',
            name='stake',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
